on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils
            l3build ctan
        name: build package with l3build
      - name: check if generated files are of latest version
        run: |
          git diff --exit-code
      - uses: actions/upload-artifact@v4
        with:
          path: |
            build/distrib/tds/
          name: presenter.tds
        name: upload build package artifacts
