on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add zip diffutils
            l3build ctan
        name: build package with l3build
      - uses: actions/upload-artifact@v2
        with:
          path: |
            build/distrib/tds/
          name: presenter.tds
        name: upload build package artifacts
