on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        name: checkout code
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add zip diffutils
            l3build ctan
        name: build package
      - uses: actions/create-release@latest
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
      - name: add presenter-ctan.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: presenter-ctan.zip
          asset_content_type: application/x-zip
      - name: add presenter.tds.zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/distrib/tds/presenter.tds.zip
          asset_content_type: application/x-zip
