on:
  push:
    branches:
    - release
    tags:
    - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        name: checkout code
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add zip diffutils
            l3build ctan
        name: build package
      - name: check if generated files are of latest version
        run: |
          git diff --exit-code
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          files: |
            texmf/doc/latex/presenter/presenter-doc.pdf
            presenter-ctan.zip
            build/distrib/tds/presenter.tds.zip
